### ISSUE TITLE
JS files are included multiple time

### ISSUE THREAD

**Issue by dnagir** [johnbintz/jasmine-headless-webkit#10]
When using Jasmin config similar to:

```
src_files:
  - app/assets/javascripts/must_be_first.js
  - app/assets/javascripts/**/**.js
```

The `must_be_first.js` is included twice. It look like there is no check for already included files when wildcards are used.

**Comment by johnbintz** [comment]
I just pushed c29757ad9f82b3602bc8714122ab294498fbd09f which should fix that issue. Take it for a spin and let me know if it works for you.

**Comment by johnbintz** [comment]
Oof, I didn't mean to close it. Stupid lack of coffee. You close it when it's fixed. :)

**Comment by dnagir** [comment]
That's fixed. But I am now getting the warning:

```
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be removed on or after 2011-11-01.
Gem.available? called from /home/dima/.rvm/gems/ruby-1.9.2-p180/gems/jasmine-1.0.2.1/lib/jasmine/base.rb:64.
```

The warning must be related to rubygems/rake that broke the world. But just thought to let you know.

**Comment by johnbintz** [comment]
Looks like an issue with jasmine-gem. There's a pull request for it: https://github.com/pivotal/jasmine-gem/pull/41
