### ISSUE TITLE
No runner found on Mac OS X Lion with Qt installed

### ISSUE THREAD

**Issue by biscuitvile** [johnbintz/jasmine-headless-webkit#104]
I'm having a very hard time figuring out the cause of this, bundle exec jasmine-headless-webkit give me this:

```
No runner found, attempting to compile...
make: *** No rule to make target `clean'.  Stop.
/Developer/Tools/Qt/moc -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I/usr/include/QtWebKit -I/usr/include -I. -F/Library/Frameworks -D__APPLE__ -D__GNUC__ Page.h -o moc_Page.cpp
make: /Developer/Tools/Qt/moc: No such file or directory
make: *** [moc_Page.cpp] Error 1
[jasmine-headless-webkit] The jasmine-headless-webkit specrunner (jasmine-webkit-specrunner) could not be found! Try reinstalling the gem. (Jasmine::Headless::NoRunnerError)
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/runner.rb:41:in `initialize'
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in `new'
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in `run!'
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/gems/jasmine-headless-webkit-0.8.4/bin/jasmine-headless-webkit:10:in `<top (required)>'
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/bin/jasmine-headless-webkit:19:in `load'
  /Users/andy/.rvm/gems/ruby-1.9.2-p290@project/bin/jasmine-headless-webkit:19:in `<main>'
```

qmake -v give me this:

```
QMake version 2.01a
Using Qt version 4.7.4 in /Library/Frameworks
```

I installed qt through homebrew and am currently using capybara-webkit without issue, which also has a qt dependency.

I'm on Mac OS X Lion using these gems:

```
jasmine (1.1.2)
jasmine-core (1.1.0)
jasmine-headless-webkit (0.8.4)
jasmine-rails (0.0.2)
```

**Comment by biscuitvile** [comment]
This boiled down to something involved with my path in .bash_profile

This helped:
https://discussions.apple.com/thread/2752621?start=0&tstart=0

And I ended up adding this to my path

```
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin"
```

Resolved my problem, but there is a still something missing in my comprehension of exactly why.

**Comment by johnbintz** [comment]
Glad you got it working. On first glance, `/Developer/Tools/Qt/moc` couldn't be found, so you'd probably need `/Developer/Tools/Qt` in your path. I'll see how capybara-webkit is handling resolving things for compilation and see if I can sync up with what they're doing.

**Comment by biscuitvile** [comment]
Thanks! Your comment is extremely helpful, as I'll probably be quicker to look at my path the next time around with something like this. Still new to the *nix-y stuff.

**Comment by jtanium** [comment]
I realize I'm late to the party, but I ran into this problem and I just symlinked the brew installed Qt to /Developer/Tools, a la:

``` bash
sudo ln -s /usr/local/Cellar/qt/4.8.0/bin /Developer/Tools/Qt
```

**Comment by billgathen** [comment]
Thanks @jtanium, symlink got me sorted right out!

**Comment by levibuzolic** [comment]
Confirmed, changing PATH to include /usr/local/bin earlier fixes it.

**Comment by garygreyling** [comment]
Thanks @jtanium, symlink got me sorted right out too!
