### ISSUE TITLE
"Spec runner interrupted" when using HEAD

### ISSUE THREAD

**Issue by christiannelson** [johnbintz/jasmine-headless-webkit#105]
I've been using HEAD to test out all of the new formatter greatness.

It looks like there's an issue with HEAD in how it reports status . JHW HEAD in conjunction with guard-jasmine-headless-webkit (v0.3.2) only reports "Spec runner interrupted" when tests run (regardless of success/failure). Dropping back to JHW (v0.8.4) works fine. I should add that I'm referring to the growl notifications.

**Comment by johnbintz** [comment]
The latest git HEADs of the guard and this gem should fix this.

**Comment by christiannelson** [comment]
@johnbintz upgraded and confirmed. thanks!
