### ISSUE TITLE
`JHW -l` not loading files in proper order

### ISSUE THREAD

**Issue by wulftone** [johnbintz/jasmine-headless-webkit#107]
I'm trying to get this gem working, but it seems to load my sprockets required files out of order.  My app works using the `test_track` gem for jasmine testing, and also works using `capybara` and the webkit driver, and as a regular app in development mode or deployed to herkou--so I know sprockets is set up correctly!

However, when I set up JHW, I get the following errors:

```
Running `bundle exec jasmine-headless-webkit -c spec/javascripts/views/homefront/users/show_spec.js.coffee`
/usr/share/themes/Felicia/gtk-2.0/gtkrc:79: Murrine configuration option "gradients" is no longer supported and will be ignored.
ReferenceError: Can't find variable: jQuery
ReferenceError: Can't find variable: jQuery
ReferenceError: Can't find variable: Homefront
ReferenceError: Can't find variable: Homefront
ReferenceError: Can't find variable: Homefront
ReferenceError: Can't find variable: Homefront
ReferenceError: Can't find variable: Homefront
ReferenceError: Can't find variable: Homefront
TypeError: Result of expression 'i' [undefined] is not a function.
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: jQuery
ReferenceError: Can't find variable: jQuery
TypeError: Result of expression 'Homefront.Models.User' [undefined] is not a constructor.
TypeError: Result of expression 'Homefront.Models.HouseholdsUser' [undefined] is not a constructor.

Test ordering seed: --seed 5481
```

Which makes sense, since when I do a `jasmine-headless-webkit -l` command, I get the following:

```
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-core-1.1.0/lib/jasmine-core/jasmine.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-core-1.1.0/lib/jasmine-core/jasmine-html.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-core-1.1.0/lib/jasmine-core/jasmine.css
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/jasmine-extensions.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/intense.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/headless_reporter_result.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/jasmine.HeadlessConsoleReporter.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/jsDump.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/beautify-html.js
/home/trevor/work/yc/app/assets/javascripts/toggle_disabled.js
/home/trevor/work/yc/app/assets/javascripts/underscore.js
/home/trevor/work/yc/app/assets/javascripts/backbone_link.js
/home/trevor/work/yc/app/assets/javascripts/models/homefront/relationship.js.coffee
/home/trevor/work/yc/app/assets/javascripts/models/homefront/household.js.coffee
/home/trevor/work/yc/app/assets/javascripts/models/homefront/account.js.coffee
/home/trevor/work/yc/app/assets/javascripts/models/homefront/households_user.js.coffee
/home/trevor/work/yc/app/assets/javascripts/models/homefront/user.js.coffee
/home/trevor/work/yc/app/assets/javascripts/models/homefront/invitation.js.coffee
/home/trevor/work/yc/app/assets/javascripts/backbone.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jquery-rails-1.0.19/vendor/assets/javascripts/jquery.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jquery-rails-1.0.19/vendor/assets/javascripts/jquery_ujs.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-core-1.1.0/lib/jasmine-core/json2.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/backbone-rails-0.5.2/vendor/assets/javascripts/underscore.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/backbone-rails-0.5.2/vendor/assets/javascripts/backbone.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rails-backbone-0.5.4/vendor/assets/javascripts/backbone_rails_sync.js
/home/trevor/work/yc/app/assets/javascripts/backbone-relational.js
/home/trevor/work/yc/app/assets/javascripts/homefront.js.coffee
/home/trevor/work/yc/app/assets/templates/homefront/index.jst.eco
...
/home/trevor/work/yc/app/assets/templates/relationships/index.jst.eco
/home/trevor/work/yc/app/assets/javascripts/backbone_base_view.js.coffee
/home/trevor/work/yc/app/assets/javascripts/backbone_rails_sync.js
/home/trevor/work/yc/app/assets/javascripts/helpers/toggle_disabled.js
/home/trevor/work/yc/app/assets/javascripts/json2.js
/home/trevor/work/yc/app/assets/javascripts/routers/homefront/home_router.js.coffee
/home/trevor/work/yc/app/assets/javascripts/routers/homefront/setup_router.js.coffee
/home/trevor/work/yc/app/assets/javascripts/sinon.js
/home/trevor/work/yc/app/assets/javascripts/underscore.string.js
/home/trevor/work/yc/app/assets/javascripts/views/homefront/index.js.coffee
...
/home/trevor/work/yc/app/assets/javascripts/views/relationships/index.js.coffee
/home/trevor/work/yc/app/assets/javascripts/application.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-spec-extras-0.0.2/vendor/assets/javascripts/jasmine-jquery.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-spec-extras-0.0.2/vendor/assets/javascripts/sinon.js
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/jasmine-spec-extras-0.0.2/vendor/assets/javascripts/jasmine-sinon.js
/home/trevor/work/yc/spec/javascripts/helpers/spec_helper.js.coffee
/home/trevor/work/yc/spec/javascripts/views/homefront/users/show_spec.js.coffee
```

The problem is clearly that it's loading a couple of jQuery-dependent files and a few of my Backbone models before it loads their dependencies (jQuery, and homefront.js.coffee are the dependencies).  Actually, looking at it closer, even if that's solved, it's still loading backbone.js way too late.

Here's my application.js

```
//= require jquery
//= require jquery_ujs
//= require json2
//= require underscore
//= require backbone
//= require backbone_rails_sync
//= require backbone_link
//= require backbone-relational
//= require homefront
//
//= require_tree ../templates
//= require_tree .
//= require_tree ./models
//= require_tree ./views
//= require_tree ./routers
```

This is the proper order of files I need... Any idea what's going on?

Thanks!

**Comment by johnbintz** [comment]
What is your `jasmine.yml` file?

**Comment by wulftone** [comment]
```
src_dir: app/assets/javascripts
asset_paths:
- app/assets/templates
- lib/assets/javascripts
- vendor/assets/javascripts

src_files:
- "**/*"

spec_dir: spec/javascripts

spec_files:
- "**/*[Ss]pec.*"

helpers:
- "helpers/**/*"
```

**Comment by johnbintz** [comment]
And what's in `/home/trevor/work/yc/app/assets/javascripts/backbone.js`?

**Comment by wulftone** [comment]
That's backbone... http://documentcloud.github.com/backbone/

**Comment by wulftone** [comment]
It's also loading a couple of things twice, like backbone.js, json2.js, and a few others.  This is because I have those in my `assets/javascripts` directory, but they also happen to be in some gems I have on my system.  These gems are NOT in my gemfile, however, and normally (using test_track or the other above mentioned app usage methods) they don't get loaded twice.

EDIT: oops, this part was my mistake in reporting the error, but it's still loads out of order

**Comment by johnbintz** [comment]
How are you running the command, then? Just `jasmine-headless-webkit`? Have you tried running using `bundle exec`? I think part of the reason JHW is getting confused is because you have a bunch of different files with the same name, so Sprockets is selecting the wrong ones. Try using `bundle exec` so those other gems don't get included in the load paths.

**Comment by wulftone** [comment]
Sorry, I'm running the `-l` command without bundle exec.  It loads only the correct included files if I do a bundle exec. My mistake!  Regardless, It's still loading them out of order... If it could just depend on application.js to determine the correct order, it wouldn't need to be specified in jasmine.yml, right?

**Comment by johnbintz** [comment]
The issue is that, since JHW needs to deal with both Sprockets-style and Jasmine-style load paths, to be backwards-compatible with the Jasmine gem, that `"**/*"` in `src_files` is still picking up everything else in your app that isn't directly included by Sprockets. There's no way to have either/or loading, since excluding one or the other will break for some segment of users. So the only solution (for now) is to be careful about what files get loaded and what load paths are given. Make sense?

**Comment by wulftone** [comment]
Yes, that makes sense.  I'm just not sure what the magic combination is.  I tried just including everything in order under `src_files`, but it didn't like that.  I haven't found any documentation about the jasmine.yml file, but I'll keep digging around.  I can't figure out how the exact order it goes through and does all the junk it does.... : |  digging... digging....

**Comment by johnbintz** [comment]
Here's something I just tried and got working: change `src_files` to be `[ 'application.js' ]`. Sprockets will still load the dependencies since everything's in your source path, but it won't grab any extra files.

**Comment by wulftone** [comment]
Awesome!  That worked!  How on earth did you find that syntax?  I still haven't found any reference materials concerning that .yml file.

**Comment by johnbintz** [comment]
The Jasmine project itself used to have a lot more detail on the syntax. Dunno if they're trying to phase it out, but basically Jasmine loads files that match `src_dir`/`src_files`, then `spec_dir`/`helpers`, then `spec_dir`/`spec_files`, as defined in `jasmine.yml`. JHW adds `src_dir` and `spec_dir` to the Sprockets load paths, so you can simply tell Jasmine loading to only look for that `application.js` file, which it finds, and then Jasmine-style loading won't look at anything else.

I'll definitely be adding that to the documentation for the next release, since it will solve a lot of problems like this for other users.

**Comment by thedeeno** [comment]
@johnbintz you may want to consider documenting [jasminerice's](https://github.com/bradphelan/jasminerice) approach which uses `spec/javascripts/spec.js[.coffee]` instead of `app/assets/javascripts/applications.js` as the sprockets manifest. This makes it easier to separate test specific javascripts. The `application.js` is explicitly required in there. 

I'm currently running into @wulftone's issue, and I'll be trying your suggestion with the jasminerice approach. I'll report back once tested.

**Comment by thedeeno** [comment]
Update: Hmm, I don't think I can leverage my `spec.js.coffee` manifest. I'm curious to try this gem out, but I'm not liking the mixing between the jasmine loader and sprockets.

Above you say that you need to support both sets of users (regular jasmine and sprockets). What do you think about creating another option in the yaml file (maybe `manifest`) which, if set, just defers all loading to the specified file and sprockets (ignoring the other options)? This seems like a clean switch and possibly isn't much different than the `vendor_assets` customization.

Thoughts?

**Comment by johnbintz** [comment]
Actually, I'm going to be moving to a different architecture altogether with this gem in the next few months. Having to support both styles of loading is not fun, and I want to be able to expand more upon what's here. This will probably be addressed in the new version of this project which I'm calling Flowerbox. That will allow for multiple styles of loading, and will be a lot more extensible.

For now, unless someone else contributes a patch, the loading style here will stay as-is and I'll be moving development like this over to the other project.

**Comment by thedeeno** [comment]
Is [flowerbox-delivery](https://github.com/johnbintz/flowerbox-delivery) a helper? Or is that the project you're moving too? I'd like to follow and help if I can.

**Comment by johnbintz** [comment]
Part of it. That will be the part that puts together things that can be run via some sort of runner (I'm envisioning multiple runners in the future, but whether or not that'll work out, I dunno). I'm still figuring things out, but once I put together some sort of roadmap (when I have time!) I'll make a more formal announcement.

Suffice it to say the architecture of the current project, while works, isn't what I'd have in mind long-term. I want to see something like RSpec meets Capybara, but with more flexibility in testing environments and test systems (for instance, being able to use the JS version of Cucumber if possible).
