### ISSUE TITLE
Testing web workers

### ISSUE THREAD

**Issue by Termina1** [johnbintz/jasmine-headless-webkit#109]
It appears to be a problem to test web workers with headless jasmine, cause I don't understand how to import js files inside worker, also I don't see the way to create worker, because all js files are included with file:// prefix, which isn't appropriate. May be you have a solution?

**Comment by johnbintz** [comment]
You can't. JHW works directly with files and doesn't spawn any sort of server. If you want to do that sort of testing, use PhantomJS or another solution that spawns a server.

**Comment by johnbintz** [comment]
Scratch that, I finally got intrigued enough with the idea of trying to add a server option for JHW that I decided to code something up. Try the `lets-run-a-server` branch of JHW and pass the `--use-server` option to the command and see how far that gets you.

The server's just a simple Rack app running on WEBrick on a separate thread that is essentially a fileserver with a document root of /, so the HTML runner file doesn't need any changes at all to work (yay, I got lucky!). Also I had to ensure that I wasn't forcing all URLs loaded by the WebKit runner to be treated as file URLs.

**Comment by johnbintz** [comment]
Er, `lets-start-a-server` branch.

**Comment by Termina1** [comment]
ok, thank you very much!

**Comment by johnbintz** [comment]
Had a chance to test this yet? I did some cleanup on the new branch and have been running all my specs via the HTTP runner for the past couple of days with no issues.

**Comment by johnbintz** [comment]
I merged in the server work. Reopen this issue if it doesn't work for you.
