### ISSUE TITLE
Output format like RSpec's --format documentation

### ISSUE THREAD

**Issue by wulftone** [johnbintz/jasmine-headless-webkit#113]
I'd like to see test descriptions in my test output instead of those lovely little `.`'s--I find it incredibly useful to remind myself that what I'm testing is still what I should be testing, especially if I'm running an older test.  Both cucumber (by default) and RSpec (with the `--format documentation` flag) support this kind of output.

Here's an example from my code:

```
#invite_to_household
  should have no errors
  invites a user to the given household
  creates a temp user if no user record matches the email provided
before validation
  associates itself via the email field with a user
```

or a more general one:

```
describe block text here
  individual test text here
  and some more testing text
  context block text
    another test
    another test
another describe block
  etc.. etc..
```

Great tool!  Hope to see it continue to grow.

**Comment by johnbintz** [comment]
This works, but I haven't gotten around to writing up the documentation yet:

`jasmine-headless-webkit -f Verbose`

**Comment by wulftone** [comment]
awesome, that does work, although I had to switch to the head revision to use it.  Thanks!

**Comment by johnbintz** [comment]
Great! I was waiting for some feedback on some other issues and haven't heard boo from them, so I'll do a release candidate today and get some feedback before doing a proper release.
