### ISSUE TITLE
I cannot see result

### ISSUE THREAD

**Issue by MarcusSjolin** [johnbintz/jasmine-headless-webkit#120]
When I run this command, I dont get any results. However my college are getting them just fine. 

I can generate a test file (HTML) So I can run it that way. However when I run jasmine-headless-webkit in Terminal (Mac OSX 10.7 Lion) I just get this:

$ jasmine-headless-webkit
Warning: multi_json is using default ok_json engine. Suggested action: require and load an appropriate JSON library.
$

Ever seen before? Have I missed something in the installation? I was doing the installation on my colleges computer as well.

I have tried uninstalling gems and cleaned all the directories. Also uninstalled qt.

I am running the 0.9.0 RC1 as I cannot get it to work with the new QT.

Anything you need please comment and I'll complement.

**Comment by johnbintz** [comment]
How did you install it? Via rubygems? Are you using Bundler and a Gemfile?

**Comment by MarcusSjolin** [comment]
Yes I used the guide on the main page. and for the 0.9.0 I checked it out from git and did rake install
Thanks for quick reply!

Even this : jasmine-headless-webkit --format Verbose
gives me the same result

I installed the multi_json and json through gem

gem install multi_json
gem install json

now it just shows nothing at all, not even that warning.

Wonder what this could be?

**Comment by johnbintz** [comment]
What does `jasmine-headless-webkit -l` report?

**Comment by johnbintz** [comment]
No feedback for a few weeks, so closing. Re-open it if you have additional information.
