### ISSUE TITLE
Running as headless returns failing error code though all tests pass

### ISSUE THREAD

**Issue by yrabinov** [johnbintz/jasmine-headless-webkit#121]
I am trying to use jasmine-headless-webkit on jenkins with ci.  When running headless either as a rake task or directly, both on jenkins and locally, all tests pass but a failing code is returned.  Here is the output:

yakbox:stageit yrabinov$ rake jasmine:headless

Running Jasmine specs...
.......................<div id="jasmine-fixtures">
  <div id="chat_loading">
  </div>
  <div id="chat_disconnected">
    &nbsp;
  </div>
  <ul id="msg_area">
  </ul>
</div>
/blah/haha"pting reconnect to get a new chat session 
/blah/haha"g reconnect to get a new chat session 
/chat/connect".............."Attempting reconnect to get a new chat session 
[object Object]" the server, new settings are: 
[object Object]" the server, new settings are: 
................................................................................................................................................................................................................................2012-02-22 18:27:30.610 jasmine-webkit-specrunner[13370:107] Error loading /Users/yrabinov/Library/Internet Plug-Ins/Google Earth Web Plug-in.plugin/Contents/MacOS/libnpgeplugin.dylib:  dlopen(/Users/yrabinov/Library/Internet Plug-Ins/Google Earth Web Plug-in.plugin/Contents/MacOS/libnpgeplugin.dylib, 265): no suitable image found.  Did find:
    /Users/yrabinov/Library/Internet Plug-Ins/Google Earth Web Plug-in.plugin/Contents/MacOS/libnpgeplugin.dylib: mach-o, but wrong architecture
2012-02-22 18:27:30.612 jasmine-webkit-specrunner[13370:107] Error loading /Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin:  dlopen(/Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin, 265): no suitable image found.  Did find:
    /Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin: mach-o, but wrong architecture
2012-02-22 18:27:30.616 jasmine-webkit-specrunner[13370:107] Error loading /Library/Internet Plug-Ins/iPhotoPhotocast.plugin/Contents/MacOS/iPhotoPhotocast:  dlopen(/Library/Internet Plug-Ins/iPhotoPhotocast.plugin/Contents/MacOS/iPhotoPhotocast, 262): no suitable image found.  Did find:
    /Library/Internet Plug-Ins/iPhotoPhotocast.plugin/Contents/MacOS/iPhotoPhotocast: mach-o, but wrong architecture
..
PASS: 285 tests, 0 failures, 1.475 secs.

Test ordering seed: --seed 5657
rake aborted!
Jasmine::Headless::ConsoleLogUsage

Tasks: TOP => jasmine:headless
(See full trace by running task with --trace)
yakbox:stageit yrabinov$ echo $?
1

Does the failure have something to do with it attempting to load chrome libraries?  Has anyone seen this?

Thanks.

**Comment by LorenzMeier** [comment]
How did yo solve this issue eventually? I seem to have a similar issue in a different application.
