### ISSUE TITLE
Working with fixtures in jasmine-headless-webkit

### ISSUE THREAD

**Issue by ghost** [johnbintz/jasmine-headless-webkit#122]
Is it possible to load fixtures via XHR in jasmine-headless-webkit? I am having trouble working with the jasmine-jquery api for loading a fixture. The error I get is:

ReferenceError: Can't find variable: fixtures in <filename>

It would be great to have support for fixture loading. I find them useful for testing complex interactions.

**Comment by johnbintz** [comment]
The only way you can do it is with an experimental server-based feature in the git HEAD version of JHW. I've been very busy lately and haven't had the time to put into working on JHW, but suffice to say if you run JHW with `--use-server` you'll be running your tests against a server that you can potentially use jasmine-jquery with.

**Comment by hlascelles** [comment]
Excellent, thanks, the server works great for me. I was seeing the following error when trying to use fixtures (in case anyone is arriving at this page via Google).

```
NETWORK_ERR: XMLHttpRequest Exception 101
```

**Comment by johnbintz** [comment]
Cool, closing.
