### ISSUE TITLE
Sprockets::FileNotFound

### ISSUE THREAD

**Issue by leequarella** [johnbintz/jasmine-headless-webkit#123]
My application.js has //= require jquery.datepick.min which is located in vendor/assets/javascripts. (There are more libs required than datepick, whichever one is listed first is the one that throws the error. Am just using datepick here as the example.)

jasmine.yml:

```
src_files:
  - "**/*"
helpers:
  - helpers/**/*
spec_files:
  - "**/*_spec.*"
src_dir:
  - app/assets/javascripts
  - vendor/assets/javascripts
spec_dir: spec/javascripts
```

When running jasmine-headless-webkit ->

```
[jasmine-headless-webkit] couldn't find file 'jquery.datepick.min'
(in /home/leequarella/workspace/rms/rails_app/app/assets/javascripts/application.js:5) (Sprockets::FileNotFound)
```

Full stacktrace: https://gist.github.com/1941032

What did I miss?

**Comment by johnbintz** [comment]
What does `jasmine-headless-webkit -l` report?

**Comment by leequarella** [comment]
https://gist.github.com/1941032

Updated to match `-l` param

**Comment by leequarella** [comment]
Some specs for reference:
Ubuntu 11.10
Ruby 1.9.3p0
Rails 3.1.3
Jamsine 1.1.2
Jasmine-headless-webkit 0.8.4

**Comment by johnbintz** [comment]
Try using git HEAD. There's been a number of fixes for Jasmine-style file finding that may have fixed the issue.

**Comment by leequarella** [comment]
0.9.0rc1

Same issue, different trace: https://gist.github.com/1941961

**Comment by johnbintz** [comment]
OK, we're going to need to dig deeper. Check out and use git HEAD and, after https://github.com/johnbintz/jasmine-headless-webkit/blob/master/lib/jasmine/headless/files_list.rb#L127, add:

`p search_paths`

and paste the result here.

**Comment by leequarella** [comment]
["/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/jasmine-core-1.1.0/lib/jasmine-core", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/bundler/gems/jasmine-headless-webkit-3f6fac9e96f1/vendor/assets/javascripts", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/handlebars_assets-0.4.1/vendor/assets/javascripts", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/jquery-rails-1.0.19/vendor/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/app/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/vendor/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/spec/javascripts"]

**Comment by johnbintz** [comment]
And it's stupid question time: the `/home/leequarella/workspace/rms/rails_app/vendor/assets/javascripts` directory has a file called `jquery.datepick.min.js` in it? If the answer to that is "yes", this becomes a Sprockets problem, since I know that the correct paths are being added to the Sprockets search.

**Comment by leequarella** [comment]
Yep, it's there.  The problem exists even if I ditch the line looking for query.datepick.min.js, things just fall apart at the next `require` line.

This particular app is fully functional and running in production, sprockets and all.  Just trying to get some javascript tests in there now.

**Comment by johnbintz** [comment]
OK, try this: after https://github.com/johnbintz/jasmine-headless-webkit/blob/master/lib/jasmine/headless/files_list.rb#L128, add:

`p @sprockets_environment`

**Comment by leequarella** [comment]
```
#<Sprockets::Environment:0x9346c88>
```

But that was boring, so I did `@sprockets_environment.inspect`

```
#<Sprockets::Environment:0x443b77e root="/home/leequarella/workspace/rms/rails_app", paths=["/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/jasmine-core-1.1.0/lib/jasmine-core", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/bundler/gems/jasmine-headless-webkit-bfda078bd73c/vendor/assets/javascripts", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/handlebars_assets-0.4.1/vendor/assets/javascripts", "/home/leequarella/.rvm/gems/ruby-1.9.3-p0/gems/jquery-rails-1.0.19/vendor/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/app/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/vendor/assets/javascripts", "/home/leequarella/workspace/rms/rails_app/spec/javascripts"], digest="a2fe3d9fc9c4f868b370b15b14e137af">
```

**Comment by johnbintz** [comment]
OK, now try in its place:

`puts @sprockets_environment.find_asset('jquery.datepick.min.js').to_s`

**Comment by leequarella** [comment]
FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

I have just wasted a day and a half of each of our times, and now I feel like a complete turd...

Your "stupid question" was dead on, the directory was singular `javascript`, not the plural `javascripts`.  I am extremely embarrassed right now and think I should disappear from the internet for a while.

I am very sorry to have wasted your time.  Thank you for being so awesome in doing everything you could to help, you are a true gentleman.

**Comment by johnbintz** [comment]
D'oh! We've all done that one. Glad you got it figured out. :)
