### ISSUE TITLE
Better error logging

### ISSUE THREAD

**Issue by leequarella** [johnbintz/jasmine-headless-webkit#125]
Is there a way to get more information about errors?  Like the line on which they are occurring?  `TypeError: 'undefined' is not a function` can be hard to track down.

It does state the line that defines the test, but more detail would be nice.

**Comment by johnbintz** [comment]
Nope, not with the existing JavaScript engine being used. [Blame WebKit](https://bugs.webkit.org/show_bug.cgi?id=66994). You have two choices:
- Run your tests in a browser using the `--use-server` option
- Wait for me to get [Flowerbox](http://github.com/johnbintz/flowerbox) to the point where it can start to replace `jasmine-headless-webkit`

This very problem, btw, is the #1 motivation for Flowerbox.
