### ISSUE TITLE
Support for js.coffee.erb files on asset pipeline

### ISSUE THREAD

**Issue by lamikae** [johnbintz/jasmine-headless-webkit#126]
Rails pipeline offers a way to compile a file through multiple targets. A coffeescript source file may be first compiled through erb renderer. Example of an use case would be to compile constants such as API keys into JS.

Current HEAD version of JHW throws a warning that js.coffee.erb files are skipped. Perhaps the full rendering with proper variables is possible, but if not, a useful workaround would be to strip the <%= %> tags away and show a warning about this, instead of skipping these files entirely. This would make possible to test the functional parts of the code that are unaffected by the values inserted by erb compiler.

More info: http://guides.rubyonrails.org/asset_pipeline.html#preprocessing

If this is a Jasmine-core issue, please close the bug and I will report this over there.

**Comment by johnbintz** [comment]
It's not really possible to evaluate ERB with the way JHW is intended to be used. JHW can be used outside of a Rails environment, so including a file with .erb requires knowledge beyond what a strictly JavaScript unit testing tool should have.

I personally have no need for that ERB support, as I don't use ERB with JavaScript, but if you want to add the stripping of ERB as an optional feature, feel free to send a pull request along. I really don't want to get in to having to provide an environment where one can potentially execute random Ruby code in what is supposed to be a JavaScript testing tool, so stripping is the only real way I would want to see that done.

**Comment by lamikae** [comment]
Ok, that's cool.
I have worked around this by creating a temporary symlink without the .erb suffix.

**Comment by lamikae** [comment]
I took your heed and wrote a patch.
https://github.com/lamikae/jasmine-headless-webkit/commit/4da25d6618b72a4733628a9c43891fde6fe5ce7c

**Comment by johnbintz** [comment]
Can you make that a pull request so that it's easier for me to look over and, if I like it, merge in?

**Comment by lamikae** [comment]
The pull request opened another issue, closing this one.
