### ISSUE TITLE
Disabling iframe.src events

### ISSUE THREAD

**Issue by lamikae** [johnbintz/jasmine-headless-webkit#127]
When testing code that sets the "src" attribute of an iframe element, the runner crashes with this message:

```
Can't load file:///..../jhw.73568.html, the file may be broken.
Out of curiosity, did your tests try to submit a form and you haven't prevented that?
Try running your tests in your browser with the Jasmine server and see what happens.
rake aborted!
Jasmine::Headless::TestFailure
```

Would it be possible to disable the iframe content fetching capability of the Qt webkit component? 
It would be enough to just test that the src attribute changed value.

**Comment by johnbintz** [comment]
I don't know off-hand. Give it a shot. I typically wrap anything like that in a function that I mock the behavior of, then have that one function be the part that actually sets the src.

**Comment by lamikae** [comment]
Good idea.
