### ISSUE TITLE
Error when using autotest, rails3, rspec2

### ISSUE THREAD

**Issue by kasima** [johnbintz/jasmine-headless-webkit#13]
Sweet project!  Though, I added .jasmine-headless-webkit, and I get:

```
loading autotest/jasmine_rails_rspec2
Autotest style autotest/jasmine_rails_rspec2 doesn't seem to exist. Aborting.
```

Which made me sad.

**Comment by johnbintz** [comment]
The Autotest support is very incomplete and will probably stay that way, as I've been moving more in the direction of using Guard with `jasmine-headless-webkit` for numerous reasons. If you want to add the necessary bits to the project to get it to work with that combination of Autotest runners, feel free, but I won't be adding them myself anytime soon.

**Comment by kasima** [comment]
Thanks for the quick reply.  I'll look into it.

K

**Comment by pirelenito** [comment]
I've come into the same issue, and fixed it by referring to the 'correct' autotest gem. 

I was using: _gem 'autotest-rails'_ but,  according to [this documentation](https://github.com/rspec/rspec-rails), the correct gem is: _gem 'autotest'_.
