### ISSUE TITLE
does not play nicely with requirejs

### ISSUE THREAD

**Issue by bigfish** [johnbintz/jasmine-headless-webkit#136]
I have a project using requireJS to load some modules. Eg, in my spec file I require a module before testing it. The spec passes when run using the jasmine gem in a browser, but it fails when run in jasmine-headless-webkit. 

Is there a way to get this to work, or is it nor supported?

It may be that requirejs is not getting configured correctly.. is it possible to use an existing HTML file rather than generating one with the jasmine.yml conf?

**Comment by johnbintz** [comment]
It won't work nicely, and I don't have time to make it work nicely right now. I'd suggest trying a different JS testing project for testing RequireJS code.

**Comment by kowal** [comment]
@johnbintz : and there is no workaround for this? some suggestions maybe how to hook into HTML generation?

**Comment by johnbintz** [comment]
There is no workaround unless someone else writes one. As this project is pretty much unsupported now, you'd be better off finding a different testing tool that will give your RequireJS support.
