### ISSUE TITLE
Issue with Date.parse

### ISSUE THREAD

**Issue by clemensp** [johnbintz/jasmine-headless-webkit#139]
Hello,

I'm currently using jasmine-headless-webkit version 0.8.4, and noticed that Date.parse fails for certain inputs:

```
it("tests Date.parse", function() {
  console.log(Date.parse("2008-Jan-18 10:31 AM"));
});
```

The above prints `JSON: Null`

If I run it in a browser, it prints `1200670260000`

Is this a bug with jasmine-headless-webkit or something else?

**Comment by johnbintz** [comment]
It's got to be something else, probably in the JavaScript engine that QtWebkit brings along. Nothing I can really do about that on my end.
