### ISSUE TITLE
A newer version of Rubygems is required to use vendored assets. Please upgrade.

### ISSUE THREAD

**Issue by RomanMinkin** [johnbintz/jasmine-headless-webkit#154]
Hi guys,

Could you help me.
When I use **rake** i get next error:

rake aborted!
A newer version of Rubygems is required to use vendored assets. Please upgrade.

Ubuntu 10.04

$ ruby -v
**ruby 1.9.2p320 (2012-04-20 revision 35421) [i686-linux]**

**$ gem list**

**\* LOCAL GEMS ***
addressable (2.2.8)
bundler (1.1.4)
childprocess (0.3.0)
coffee-script (2.2.0)
coffee-script-source (1.2.0)
colored (1.2)
diff-lcs (1.1.3)
execjs (1.4.0, 1.2.13)
faraday (0.8.1)
ffi (1.0.11)
github_api (0.5.4)
hashie (1.2.0)
hike (1.2.1)
httpauth (0.1)
jasmine (1.2.0, 1.1.2)
jasmine-core (1.2.0, 1.1.0)
jasmine-headless-webkit (0.8.4)
kicker (2.5.0)
libwebsocket (0.1.3)
mime-types (1.18)
multi_json (1.3.6, 1.0.4)
multipart-post (1.1.5)
nokogiri (1.5.3)
oauth2 (0.7.1)
rack (1.4.1, 1.4.0)
rainbow (1.1.3)
rake (0.9.2.2)
rb-fsevent (0.9.1)
rest-client (1.6.7)
rspec (2.8.0)
rspec-core (2.10.1, 2.8.0)
rspec-expectations (2.10.0, 2.8.0)
rspec-mocks (2.10.1, 2.8.0)
rubygems-bundler (1.0.3)
rubygems-update (1.8.24)
rubyzip (0.9.5)
rvm (1.11.3.4)
selenium-webdriver (2.17.0)
sprockets (2.3.0)
thor (0.15.2)
tilt (1.3.3)
uglifier (1.0.4)

Thank you!

**Comment by johnbintz** [comment]
What does `gem -v` report?

**Comment by RomanMinkin** [comment]
Hi John,

> $ gem -v
> 1.8.24
> 
> $ which qmake
> /usr/local/Trolltech/Qt-4.7.0/bin/qmake
> 
> $ qmake -v
> QMake version 2.01a
> Using Qt version 4.7.0 in /usr/local/Trolltech/Qt-4.7.0/li
> 
> $ which qmake-qt4
> (nothing, i've been removed it)

**Comment by RomanMinkin** [comment]
John,

I found where problem was , in `ruby` version.

$ ruby -v shown

> ruby 1.9.2p320 (2012-04-20 revision 35421) [i686-linux]

But `RUBY_VERSION` in `Rakefile` has shown 1.8

it helps:

> rvm --default use 1.9.2

And in the end to avoid some errors I rebuilt all the gems by:

> gem update --system
> gem pristine --all
