### ISSUE TITLE
Better backtrace for errors

### ISSUE THREAD

**Issue by dlee** [johnbintz/jasmine-headless-webkit#155]
I'm not getting a backtrace for errors. This other person seems to have the same problem:
http://stackoverflow.com/questions/10930022/jasmine-debugging-backtrace-using-jasmine-headless-webkit-on-ror?rq=1

The homepage for jasmine-headless-webkit says that it "provides cleaner debugging and backtrace output". Are backtraces not supported, or am I not configuring/running it properly?

**Comment by johnbintz** [comment]
Backtraces are not supported, nor will they be until Qt makes them available in QtWebkit. I haven't checked the status of this in quite a while, as other projects have been taking up my time.

**Comment by dlee** [comment]
@johnbintz Thanks for the heads up. Why does the homepage say that it "provides cleaner debugging and backtrace output"?

**Comment by johnbintz** [comment]
Because it hasn't been updated in forever and probably won't be updated for quite a while unless someone else makes that change. Other projects have taken my time away from JHW and I don't know when I'm going to get it back.
