### ISSUE TITLE
How to get callstack?

### ISSUE THREAD

**Issue by pschuegr** [johnbintz/jasmine-headless-webkit#176]
Sorry if there's an obvious answer to this question:

How do I get the callstack from an error?  All I'm seeing is the location of the error in the spec file.

Analytics after init, initialized is set to true. (/opt/blah/blah/spec/javascripts/analytics_spec.js:6)
  TypeError: 'undefined' is not a function

Knowing where the error actually occurred would be much more helpful.

**Comment by johnbintz** [comment]
You can't. It's a limitation of the QWebKit widget. Since this project isn't being actively maintained anymore, you should look into switching to another JS test runner, like testem or testacular. They provide call stacks.

**Comment by pschuegr** [comment]
Thanks John.
