### ISSUE TITLE
Using jquery-rails

### ISSUE THREAD

**Issue by lunks** [johnbintz/jasmine-headless-webkit#21]
There is no documentation on how you can use JQuery and JQuery-UI when they are bundled with jquery-rails. Is there an easy way to require them on your tests?

**Comment by johnbintz** [comment]
Are you talking about with Rails 3.1 assets? If so, you'll need to precompile your JS assets before use, which will include jQuery with your application, as jasmine-headless-webkit can't easily integrate that tightly with Rails. You can use jasmine-headless-webkit with [Guard](https://github.com/guard/guard) and [guard-rails-assets](https://github.com/dnagir/guard-rails-assets) to precompile your assets before running tests with [guard-jasmine-headless-webkit](http://github.com/guard/guard-jasmine-headless-webkit):

```
guard 'rails-assets' do
  watch(%r{app/assets/.*\.(js|coffee)$})
end

guard 'jasmine-headless-webkit' do
  watch(%r{public/assets/.*\.js})
end
```

**Comment by lunks** [comment]
Yes, I do mean Rails 3.1 assets.
I don't have Guard on my project yet, but this might be the perfect excuse to set it up. :)

Thanks a lot!
