### ISSUE TITLE
problem running jasmine-headless-webkit

### ISSUE THREAD

**Issue by lporras** [johnbintz/jasmine-headless-webkit#29]
Hi,

When I run jasmine-headless-webkit without specify any file, it is not run all spec files.
In my jasmine.yml I have: 
   spec_files:
- *_/_[sS]pec.js

I am running my tests in this way: jasmine-headless-webkit spec/javascripts/_/_[sS]pec.js spec/javascripts/*[sS]pec.js

**Comment by johnbintz** [comment]
This fix just uses `Dir.[]`, it should cover your use case.
