### ISSUE TITLE
Jasmine headless webkit won't build native extension

### ISSUE THREAD

**Issue by agmcleod** [johnbintz/jasmine-headless-webkit#32]
Environment:
Ruby 1.9.2p136
using RVM
Mac OS X 10.6

Here's the output from when running bundle install. The same thing happens when I use gem install as well:

Installing jasmine-headless-webkit (0.4.2) with native extensions /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:533:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/bin/ruby extconf.rb 
```

make: **\* No targets specified and no makefile found.  Stop.

Gem files will remain installed in /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/jasmine-headless-webkit-0.4.2 for inspection.
Results logged to /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/jasmine-headless-webkit-0.4.2/ext/jasmine-webkit-specrunner/gem_make.out
    from /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:511:in `block in build_extensions'
    from /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in`each'
    from /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in `build_extensions'
    from /Users/aaronmcleod/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:159:in`install'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/source.rb:101:in `block in install'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:78:in`preserve_paths'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/source.rb:91:in `install'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/installer.rb:58:in`block (2 levels) in run'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:93:in `with_build_args'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/installer.rb:57:in`block in run'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `block in each'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in`each'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `each'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/installer.rb:49:in`run'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/installer.rb:8:in `install'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/cli.rb:222:in`install'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/vendor/thor/invocation.rb:118:in`invoke_task'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/vendor/thor.rb:246:in `dispatch'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/lib/bundler/vendor/thor/base.rb:389:in`start'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/gems/bundler-1.0.15/bin/bundle:13:in `<top (required)>'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/bin/bundle:19:in`load'
    from /Users/aaronmcleod/.rvm/gems/ruby-1.9.2-p136/bin/bundle:19:in `<main>'

**Comment by johnbintz** [comment]
Can you check out the latest git HEAD and then run the following from within the checked out repo:

``` bash
cd ext/jasmine-webkit-specrunner
ruby extconf.rb
```

And see what output you get?

**Comment by agmcleod** [comment]
Here's my entire output:

aaronmcleod@MacBook-Pro $ git clone http://github.com/johnbintz/jasmine-headless-webkit.git
Cloning into jasmine-headless-webkit...
remote: Counting objects: 1046, done.
remote: Compressing objects: 100% (510/510), done.
remote: Total 1046 (delta 540), reused 956 (delta 450)
Receiving objects: 100% (1046/1046), 223.37 KiB | 3 KiB/s, done.
Resolving deltas: 100% (540/540), done.
aaronmcleod@MacBook-Pro $ cd jasmine-headless-webkit/
aaronmcleod@MacBook-Pro $ cd ext/jasmine-webkit-specrunner/
aaronmcleod@MacBook-Pro $ ruby extconf.rb
make: **\* No targets specified and no makefile found.  Stop.
aaronmcleod@MacBook-Pro $

**Comment by johnbintz** [comment]
What does running `qmake -spec macx-g++` in that directory return?

**Comment by agmcleod** [comment]
-bash: qmake: command not found

I'm trying to install qt4-mac through ports now. I'll let you know if that fixes it.

**Comment by agmcleod** [comment]
After installing qt, i was able to bundle install. I'll close the issue.

Thanks for your help :)

**Comment by papercheck** [comment]
I had a similar issue and my environment is as follows:
Ruby ree-1.8.7-2011.03
using RVM
Ubuntu 11.04

I then installed: qt4-qmake and libqt4-dev, which resolved this issue.
`sudo apt-get install libqt4-dev`
`sudo apt-get install qt4-qmake`

**Comment by agmcleod** [comment]
Yeah, same deal for me. More specifically

``` bash
sudo port install qt4-mac
```

**Comment by johnbintz** [comment]
I think I'll be adding friendlier notices to `extconf.rb` so folks know just what's going on. Thanks, all!

**Comment by papercheck** [comment]
Hi, John,

Locally I have been able to get jasmine-headless-webkit installed. It is 
a pretty neat library, thank you so much for providing excellent 
documentation and support! One thing you may want to consider is either 
using an older version of Qmake or not using it at all. After I got this 
gem to properly install on my local Ubuntu machine, I had a very 
difficult time getting this gem to install on Ubuntu 9.10 (which happens 
to be our staging server for CruiseControl). I had to compile Qmake from 
source. In any case, I am really excited to use this in our project. I 
also wrote some documentation for the rest of our staff. Please feel 
free to use it modify it, etc.

```
  Running Jasmine on CruiseControl.rb
```

There is a way to run Jasmine using|rake jasmine:ci|, however, this 
opens up a browser (pops the browser), and does not work with our 
staging cruisecontrol.rb implementation, as it does not have FireFox 
installed. The preferred method is using_Jasmine Headless WebKit_. You 
will need to install a gem in the Gemfile,|gem 
"jasmine-headless-webkit", "~> 0.5.0"|. This is gem is very_edge_, and 
requires:

|  coffee-script>= 2.2
  jasmine ~>  1.1.beta
  rainbow>= 0
|

The gem is compiled using_qt4-qmake_and you may run into problems if 
this is not installed. To test if it is installed, you should run|qmake 
--version|and you should receive something like:

|  QMake version 2.01a
  Using Qt version 4.7.2 in /usr/lib
|

If you receive a different message, you can install qt4-qmake using the 
following commands as root:

_Linux Ubuntu 11.04_

|  sudo apt-get install libqt4-dev
  sudo apt-get install qt4-qmake
|

_Mac OS X 10.6_

|  sudo port install qt4-mac
|

On the staging server, running Ubuntu 9.10, running|sudo apt-get install 
libqt4-dev|and|sudo apt-get install qt4-qmake|will install qt4, but it 
installs_version 4.5.2_, which will not be able to install|gem 
"jasmine-headless-webkit", "~> 0.5.0"|, as it requires Qt 4.7 or later 
version. You will need to compile qt4-qmake from sourceQt version 4.7.0 
http://get.qt.nokia.com/qt/source/qt-everywhere-opensource-src-4.7.0.tar.gz. 
There are excellentdirections 
http://doc.qt.nokia.com/latest/install-x11.htmlon how to compile the 
source code.

-Darren

**Comment by johnbintz** [comment]
Thanks for the version reminder. I'll add that to the checks. Great docs, too!

**Comment by johnbintz** [comment]
@papercheck, want to add that guide to the project wiki? The wiki's pretty sparse, but I'd love to start fleshing it out with things like this, instead of leaving this buried in a ticket no one will ever see (but might want to).

**Comment by papercheck** [comment]
Hello, John,

That sounds great! I would love to contribute. Though your instructions are pretty straightforward. It was just the bit about Qt. 

-Darren

## -Darren

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

johnbintz reply@reply.github.com wrote:

@papercheck, want to add that guide to the project wiki? The wiki's pretty sparse, but I'd love to start fleshing it out with things like this, instead of buried in a ticket no one will ever see.

##
