### ISSUE TITLE
Cannot Connect to X Server (Workaround Using Xvfb)

### ISSUE THREAD

**Issue by papercheck** [johnbintz/jasmine-headless-webkit#34]
Environment:
Ubuntu: 9.10
Ruby : ree-1.8.7-2011.03
RVM

I am trying to use Jasmine with cruisecontrol.rb. However, I hit a snag, I am receiving an error message that reads:

```
 jasmine-webkit-specrunner: cannot connect to X server
 rake aborted!
```

I started researching this error and came across Xvfb or virtual framebuffer Xserver for Version 11 [Xvfb Manpages](http://manpages.ubuntu.com/manpages/natty/man1/Xvfb.1.html). The particular staging server we are working with does not have a display which I tested using `echo $DISPLAY`. 

Does jasmine-headless-webkit require a display? If so, is there an option to use Xvfb instead? 

I did find a work around for this problem using Xvfb:
1.  `sudo apt-get install xvfb`
2.  run `Xvfb :99 -ac` and resolve missing dependencies. 
   -        `sudo apt-get install x11-xkb-utils`
   -        `sudo apt-get install xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic`
   -        `sudo apt-get install xserver-xorg-core`
3. Use Xvfb to run the headless rake command `xvfb-run rake jasmine:headless` or `xvfb-run jasmine-headless-webkit -c`

Reference: [MARTIN DALE LYNESS](http://blog.martin-lyness.com/archives/installing-xvfb-on-ubuntu-9-10-karmic-koala)

**Comment by johnbintz** [comment]
It definitely does. [capybara-webkit](http://github.com/thoughtbot/capybara-webkit) has the best guide for getting displays up and running with QtWebKit widget-based projects, so I just point people there in the docs and save myself the trouble of duplicating their effort. Running how you do w/ `xvfb-run` is the best option so far (unless you can come up with a nicely integrated one and send a pull request! :) )

**Comment by papercheck** [comment]
Thank you for the prompt response! I read the documentation and it appears that [capybara-webkit](https://github.com/thoughtbot/capybara-webkit) is using Xvfb:

```
   On Linux platforms, capybara-webkit requires an X server to run, 
   although it doesn't create any visible windows. Xvfb works 
   fine for this. You can setup Xvfb yourself and set a DISPLAY 
   variable.
```

I will see if I can integrate Xvfb. That would make this a lot less complex, but then again, what fun would that be?

**Comment by rearviewmirror** [comment]
centos 5.9, cucumber 1.3.3, webkit 0.14.23
(If anyone like me comes here with the below msg)

Xlib: connection to ":99.0" refused by server
Xlib: Invalid MIT-MAGIC-COOKIE-1 key
webkit_server: cannot connect to X server :99
/usr/bin/xvfb-run: line 171: kill: (28389) - No such process

Possibly X11 server isn't running or not running properly, just delete the file from /tmp/.X99-lock
should be alright afterwards.
