### ISSUE TITLE
Qmake issues during gem install?

### ISSUE THREAD

**Issue by cainus** [johnbintz/jasmine-headless-webkit#42]
Can anyone suggest what I might've done wrong here (on Ubuntu)?  Thanks!
# qmake -v

QMake version 2.01a
Using Qt version 4.7.0 in /root/qt/qt-4.7.0/lib
# gem install jasmine-headless-webkit

Building native extensions.  This could take a while...
ERROR:  Error installing jasmine-headless-webkit:
    ERROR: Failed to build gem native extension.

```
    /usr/local/rvm/rubies/ruby-1.8.7-p334/bin/ruby extconf.rb
```

/usr/local/rvm/gems/ruby-1.8.7-p334@enterprise/gems/jasmine-headless-webkit-0.6.1/lib/qt/qmake.rb:145:in `check_qmake_version!': undefined method`strip' for Qt::Qmake:Class (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.8.7-p334@enterprise/gems/jasmine-headless-webkit-0.6.1/lib/qt/qmake.rb:32:in `make!'
    from extconf.rb:5

Gem files will remain installed in /usr/local/rvm/gems/ruby-1.8.7-p334@enterprise/gems/jasmine-headless-webkit-0.6.1 for inspection.
Results logged to /usr/local/rvm/gems/ruby-1.8.7-p334@enterprise/gems/jasmine-headless-webkit-0.6.1/ext/jasmine-webkit-specrunner/gem_make.out

**Comment by johnbintz** [comment]
I must've hit my head before I wrote that code. Try the latest git head and see if that works better.

**Comment by cainus** [comment]
Still no luck (and still ubuntu). Any ideas?  Thanks!

# qmake -v

QMake version 2.01a
Using Qt version 4.7.0 in /root/qt/qt-4.7.0/lib

# rake

Switching to 1.8.7
bash: /root/.rvm/scripts/rvm: No such file or directory
Using rake (0.8.7) 
Using coffee-script-source (1.1.1) 
Using multi_json (1.0.3) 
Using execjs (1.2.1) 
Using coffee-script (2.2.0) 
Using diff-lcs (1.1.2) 
Using fakefs (0.3.2) 
Using growl (1.0.3) 
Using thor (0.14.6) 
Using guard (0.5.1) 
Using guard-coffeescript (0.3.2) 
Using guard-rspec (0.4.0) 
Using guard-shell (0.1.1) 
Using jasmine-core (1.1.0.rc3) 
Using rainbow (1.1.1) 
Using jasmine-headless-webkit (0.6.2) from source at . 
Using mocha (0.9.12) 
Using rspec-core (2.6.4) 
Using rspec-expectations (2.6.0) 
Using rspec-mocks (2.6.0) 
Using rspec (2.6.0) 
Using bundler (1.0.15) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
(in /var/lib/jenkins/jobs/jasmine/jasmine-headless-webkit)
/usr/local/rvm/rubies/ruby-1.8.7-p334/bin/ruby -S bundle exec rspec ./spec/bin/jasmine-headless-webkit_spec.rb ./spec/lib/qt/qmake_spec.rb ./spec/lib/jasmine/files_list_spec.rb ./spec/lib/jasmine/headless/options_spec.rb ./spec/lib/jasmine/headless/runner_spec.rb ./spec/lib/jasmine/headless/task_spec.rb ./spec/lib/jasmine/template_writer_spec.rb
qmake is not version 4.7 or above (currently version 4.6.2. You'll need to install version 4.7 or higher
to build jasmine-headless-webkit. sudo apt-get install libqt4-dev qt4-qmake on Debian-based systems, or downloading
Nokia's prebuilt binary at http://qt.nokia.com/downloads/ should do it for you.
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -o specrunner.o specrunner.cpp
specrunner.cpp:32:2: error: #error Use Qt 4.7 or later version
specrunner.cpp:64: warning: unused parameter ‘frame’
specrunner.cpp:64: warning: unused parameter ‘msg’
specrunner.cpp:75: warning: unused parameter ‘frame’
make: **\* [specrunner.o] Error 1
Running Jasmine specs...
.... [omitted a bunch of failing tests]

**Comment by johnbintz** [comment]
Can you cd to `ext/jasmine-headless-specrunner` and run `ruby extconf.rb` directly and post the results?

**Comment by johnbintz** [comment]
Oh, your version of Qt is not new enough. You have 4.6.2 installed. Upgrade Qt and that should solve the problem.

**Comment by johnbintz** [comment]
Wait, no, you have two qmakes installed? And the install is not finding the right one?

**Comment by cainus** [comment]
There might be some 4.6.x version installed somewhere, but clearly 4.7 is installed (from my top line), and it's the one in the path... I'm not sure if the gem is detecting location incorrectly, or if I've screwed something up on this end...

**Comment by cainus** [comment]
extconf.rb output:

# ruby extconf.rb

qmake is not version 4.7 or above (currently version 4.6.2. You'll need to install version 4.7 or higher
to build jasmine-headless-webkit. sudo apt-get install libqt4-dev qt4-qmake on Debian-based systems, or downloading
Nokia's prebuilt binary at http://qt.nokia.com/downloads/ should do it for you.
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -o specrunner.o specrunner.cpp
specrunner.cpp:32:2: error: #error Use Qt 4.7 or later version
specrunner.cpp:64: warning: unused parameter ‘frame’
specrunner.cpp:64: warning: unused parameter ‘msg’
specrunner.cpp:75: warning: unused parameter ‘frame’
make: **\* [specrunner.o] Error 1

# qmake -v

QMake version 2.01a
Using Qt version 4.7.0 in /root/qt/qt-4.7.0/lib

**Comment by johnbintz** [comment]
What does `which qmake-qt4` and `which qmake` return?

**Comment by cainus** [comment]
Yeah...that exposes it...  I'll fix the symbolic link for qmake-qt4 and retry...

root@jenkins:/var/lib/jenkins/jobs/jasmine/jasmine-headless-webkit/ext/jasmine-webkit-specrunner# which qmake-qt4
/usr/bin/qmake-qt4
root@jenkins:/var/lib/jenkins/jobs/jasmine/jasmine-headless-webkit/ext/jasmine-webkit-specrunner# which qmake
/usr/bin/qmake
root@jenkins:/var/lib/jenkins/jobs/jasmine/jasmine-headless-webkit/ext/jasmine-webkit-specrunner# qmake-qt4 -v
QMake version 2.01a
Using Qt version 4.6.2 in /usr/lib
root@jenkins:/var/lib/jenkins/jobs/jasmine/jasmine-headless-webkit/ext/jasmine-webkit-specrunner# qmake -v
QMake version 2.01a
Using Qt version 4.7.0 in /root/qt/qt-4.7.0/lib

**Comment by cainus** [comment]
It seems like qmake-qt4 is the default qmake that your script uses and the fallback is qmake ... so I just rm'ed qmake-qt4 so it could fallback to my valid qmake ... Everything looks great now, except for my failing tests.  ;)

Thanks for the help!

**Comment by johnbintz** [comment]
No problem! I think I'm going to rearrange it a bit so if there are two qmakes found, it will use the "newest" if one of those is Qt 4.7+.

**Comment by johnbintz** [comment]
Try the latest head, it should find the different qmakes (and their correct versions) much more accurately.

**Comment by taimoor** [comment]
sudo apt-get install qt5-default
worked for me
http://stackoverflow.com/questions/16607003/qmake-could-not-find-a-qt-installation-of
