### ISSUE TITLE
Can't find variable: JHW in specrunner.$$.html

### ISSUE THREAD

**Issue by deleteme** [johnbintz/jasmine-headless-webkit#46]
I would like to use the `--keep` flag, but it makes an HTML file with a javascript error.

The error seems to be with the jasmine headless webkit object `JHW`, not with any of my code.

```
ReferenceError: Can't find variable: JHW
jasmine.headless-reporter.js:111ReferenceError: Can't find variable: JHW
```

Which points to:

```
JHW.specFailed(spec.getSpecSplitName().join('||'));
```

I have a fresh install of jasmine and jasmine-headless-webkit in my project.

```
jasmine (1.0.2.1)
jasmine-core (1.1.0.rc3)
jasmine-headless-webkit (0.6.1)
```

**Comment by johnbintz** [comment]
Ah, you're trying to re-open the page in a browser? Before this point, I'll say they weren't meant to be used that way. After this point, I can see the value of having a simple handler for the JHW code that mimics what the Qt runner does, maybe just writing basic results to the document somewhere like what the Jasmine gem does.

I'm refactoring all the C++ code right now, cleaning it up a lot and making it easier to plug other reporters in. Probably won't be able to get to this myself in a week or two, but if you have time, I'd definitely accept some CoffeeScript that mimics the JHW object that's defined in the C++ code, even if, for now, it just does a ton of `console.log`s.

**Comment by deleteme** [comment]
Ah, well, I was under the impression that I could use the rendered HTML files as test runners. Now I see that they are intended to allow you to see the rendered coffee script.

**Comment by deleteme** [comment]
I'm going to close this issue, as it's not really a bug. However, to avoid any future confusion, this page http://johnbintz.github.com/jasmine-headless-webkit/ could be updated to mention that the html files are not test runners.
