### ISSUE TITLE
Using run(), and waits() methods

### ISSUE THREAD

**Issue by lporras** [johnbintz/jasmine-headless-webkit#56]
I have a spec file where I have 2 calls to run(), and a waits(15500), when I run this spec I get this message: WARNING: too many runs and the test is still not finished!, I found that if I reduce the number of milliseconds in the waits() method until 5457 the tests passed, with a greater number the messages appear

**Comment by johnbintz** [comment]
There's a magic number timeout in the spec runner, a holdover from its earlier days. I'll take a closer look into it later this week and come up with a solution, probably a combination of being able to provide a timeout and a way for Jasmine to notify the runner that it's still alive and not locked.

**Comment by johnbintz** [comment]
See if that works better for you. The runner always times out if nothing happens after five second, but `waits` and `waitsFor` pause that internal timer.

**Comment by johnbintz** [comment]
I'm gonna close this, it's working fine in the tests. If you are still having issues, reopen this, er, issue.
