### ISSUE TITLE
Xvfb error in 0.7.1 gem

### ISSUE THREAD

**Issue by jonmc12** [johnbintz/jasmine-headless-webkit#65]
We recently updated to the version 0.7.1 jasmine-headless-webkit gem.  The new version runs fine on development machines (osx), however, when we run on our CI server using Xvfb, we get a new error.  0.6.3 works on both environments.

Xvfb command:

Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>&1 &
xdpyinfo -display :0 &>/dev/null && export DISPLAY=:0
xvfb-run.sh -e /tmp/LPSDEBUG -n 99 -s "-fp /usr/share/X11/fonts/misc" rake app:jasmine:run_coffee_specs

btw, rake app:jasmine:run_coffee_specs is a custom rake task that calls "bundle exec jasmine-headless-webkit spec/javascripts/coffee/*_/_.coffee"

Error message on CI server:

No runner found, attempting to compile...
Including Facter allows for detection of # of cpus, resulting in faster compilations.
make: **\* No rule to make target `clean'.  Stop.
make: *** No rule to make target`clean'.  Stop.
which: no qmake-qt4 in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)
which: no qmake in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)
  qmake is not installed or is not the right version (jasmine-headless-webkit needs Qt 4.7 or above).
  You'll need to install it to build jasmine-headless-webkit.
          sudo apt-get install libqt4-dev qt4-qmake on Debian-based systems, or downloading
  Nokia's prebuilt binary at http://qt.nokia.com/downloads/ should do it for you.
which: no qmake-qt4 in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)
which: no qmake in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)
[jasmine-headless-webkit] The jasmine-headless-webkit specrunner (jasmine-webkit-specrunner) could not be found! Try reinstalling the gem. (Jasmine::Headless::NoRunnerError)
  /var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.7.1/lib/jasmine/headless/runner.rb:36:in `initialize'
  /var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.7.1/bin/jasmine-headless-webkit:19:in`new'
  /var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.7.1/bin/jasmine-headless-webkit:19:in `<top (required)>'
  /var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin/jasmine-headless-webkit:19:in`load'
  /var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin/jasmine-headless-webkit:19:in `<main>'
true

**Comment by johnbintz** [comment]
What does `which qmake` and `which qmake-qt4` return? What OS are you running?

**Comment by jonmc12** [comment]
which qmake:
/usr/local/Trolltech/Qt-4.7.4/bin/qmake

which qmake-qt4:
which: no qmake-qt4 in (/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)

We are using Red Hat Enterprise Linux Server release 5.6 (Tikanga)

**Comment by johnbintz** [comment]
The Qt directory (`/usr/local/Trolltech/Qt-4.7.4/bin`) is not in your path. From your CI server's output:

``` bash
which: no qmake in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin)
```

**Comment by jonmc12** [comment]
I went ahead and included that in the explicit path, and it gave some error messages, but the test seemed to pass.

I'm kinda surprised this worked, since it was not necessary in v0.6.3, however, impressed the fallback did the trick.

Something definitely changed from 0.6.3 to 0.7.1 with regards to how its running in Xvfb, but we're unblocked for now using 0.7.1 which is great.

Including Facter allows for detection of # of cpus, resulting in faster compilations.
make: **\* No rule to make target `clean'.  Stop.
which: no qmake-qt4 in (/var/lib/jenkins/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin:/var/lib/jenkins/.rbenv/versions/1.9.2-p290/bin:/var/lib/jenkins/.rbenv/libexec:/usr/X11R6/bin:/var/lib/jenkins/.rbenv/shims:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/var/lib/jenkins/.rbenv/bin:/usr/local/Trolltech/Qt-4.7.4/bin)
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o Page.o Page.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o Runner.o Runner.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o ConsoleOutput.o ConsoleOutput.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o ReportFileOutput.o ReportFileOutput.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o specrunner.o specrunner.cpp
/usr/local/Trolltech/Qt-4.7.4/bin/moc -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. Page.h -o moc_Page.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o moc_Page.o moc_Page.cpp
/usr/local/Trolltech/Qt-4.7.4/bin/moc -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. Runner.h -o moc_Runner.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtWebKit -I/usr/local/Trolltech/Qt-4.7.4/include -I. -o moc_Runner.o moc_Runner.cpp
g++ -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib -o jasmine-webkit-specrunner Page.o Runner.o ConsoleOutput.o ReportFileOutput.o specrunner.o moc_Page.o moc_Runner.o    -L/usr/local/Trolltech/Qt-4.7.4/lib -lQtWebKit -lQtGui -L/usr/local/Trolltech/Qt-4.7.4/lib -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 

Running Jasmine specs...
......................................................................................................
PASS: 102 tests, 0 failures, 0.272 secs.
Triggering a new build of Handl-Server #147
Finished: SUCCESS

**Comment by johnbintz** [comment]
A lot of the Qt building code was changed around the time of 0.7.0. to make problems a lot easier to track down. I'm actually surprised the old version worked too, considering that you needed qmake or qt4-qmake on your path anyway to get the compilation to work. Oh well. Closing.
