### ISSUE TITLE
respect default value for spec_files in jasmine.yml

### ISSUE THREAD

**Issue by adamjmurray** [johnbintz/jasmine-headless-webkit#69]
The jasmine.yml file produced by jasmine init has an empty entry for:

spec_files:

According to the comments in that file, the default value is: ["*_/_[sS]pec.js"]

But jasmine-headless-webkit does not respect that default. I had to explicitly set it, otherwise it never finds any tests to run.

**Comment by johnbintz** [comment]
What does the directory structure of the file you are attempting to test look like, and what's in your current `jasmine.yml` file?

**Comment by adamjmurray** [comment]
Hmm, I thought I responded already but I guess I forgot to submit my comment :(

I was using the default jasmine.yml file produced by "jasmine init". It was at the usual location: specs/javascripts/support/jasmine.yml

The spec_files portion of the file was blank:

```
# spec_files
#
#  Return an array of filepaths relative to spec_dir to include.
# Default: ["**/*[sS]pec.js"]
#
# EXAMPLE:
#
# spec_files:
#   - **/*[sS]pec.js
#
spec_files:

```

This works fine with "rake jasmine". It picks up all specs by default, as mentioned in the comments.

To get things working with jasmine-headless-webkit, I had to change that setting to:

```
spec_files:
  - "**/*[Ss]pec.{js,coffee}"
```

It's not a big deal, but it threw me off track for a while and I wasn't sure if it was a bug in your gem. So it might just be something to note in the documentation.

**Comment by johnbintz** [comment]
OK, check out 894b979674f9d0ea9ad38a6f84cc9b91063ba905, that should fix the issue.

**Comment by johnbintz** [comment]
Closing this, if it's still broken for you then reopen it.
