### ISSUE TITLE
jasmine-headless-webkit install failure

### ISSUE THREAD

**Issue by greezeyfreezey** [johnbintz/jasmine-headless-webkit#75]
Hi,
i was following this doc http://johnbintz.github.com/jasmine-headless-webkit/

I am running ubuntu 10.04 and i grabbed qmake from http://doc.qt.nokia.com/latest/install-x11.html an followed the instructions on install. 

qmake output

qmake -v
QMake version 2.01a
Using Qt version 4.7.0 in /usr/lib/qt4/lib

when i try to install the jasmine webkit i get

gem install jasmine-headless-webkit
Building native extensions.  This could take a while...
ERROR:  Error installing jasmine-headless-webkit:
    ERROR: Failed to build gem native extension.

```
    /opt/ruby-enterprise-1.8.7/bin/ruby extconf.rb
```

/usr/lib/qt4/bin/qmake -spec /usr/lib/qt4/mkspecs/linux-g++ -o Makefile specrunner.pro
rm -f moc_Page.cpp moc_Runner.cpp
rm -f Page.o Runner.o ConsoleOutput.o ReportFileOutput.o specrunner.o moc_Page.o moc_Runner.o
rm -f *~ core *.core
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/facter-1.5.8/lib/facter.rb:143:in `method_missing': Could not find fact 'processorcount' (NoMethodError)
    from /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/jasmine-headless-webkit-0.7.2/lib/qt/qmake.rb:108:in`number_of_cpus'
    from /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/jasmine-headless-webkit-0.7.2/lib/qt/qmake.rb:52:in `make_options'
    from /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/jasmine-headless-webkit-0.7.2/lib/qt/qmake.rb:48:in`make!'
    from extconf.rb:8

**Comment by johnbintz** [comment]
I just pushed out 0.7.3.1 which rips out the cpu detection code. That code's going to become moot anyway when the new C++ runner, which is much smaller, is introduced in 0.8. Try the newest release and let me know if it works.

**Comment by greezeyfreezey** [comment]
perfect thanks!
