### ISSUE TITLE
Verbose reports

### ISSUE THREAD

**Issue by gfrivolt** [johnbintz/jasmine-headless-webkit#83]
How can I set the get the full specification like listing of the tests instead of the '.......'  format?

As I test using guard, the set of actually executed tests is rather  small, I find listing the full specification lines more useful. Thanks for helping out with a tip for configuring jasmine-headless-webkit.

As I did not find the anwser at the documentation I tried to get an answer also at http://stackoverflow.com/questions/8157817/documentation-style-spec-running-for-jasmine-headless-webkit.

Thanks for help!

**Comment by johnbintz** [comment]
This will come with it's possible to swap out reporters, which it's not possible to do yet. That is next on the list of things to do, after I get the kinks with Sprockets integration worked out.

If you like, you can take a crack at writing a new reporter with a more verbose format, in anticipation of the time when reporters can be swapped. Look at `vendor/assets/coffeescripts/jasmine.HeadlessReporter.coffee` to see how the current reporter is built.

**Comment by johnbintz** [comment]
If you've had any time to mess with making a verbose reporter, you can now bring it in using the new reporters support in git HEAD. Take a look at the restructured `vendor/assets/coffeescripts/jasmine.HeadlessReporter.Console.coffee` to see how to do it.

**Comment by johnbintz** [comment]
A Verbose reporter is now available in git master HEAD:

`jasmine-headless-webkit -f Verbose`

Try it out and let me know what you think. If you have any issues with it, reopen this ticket.
