### ISSUE TITLE
Add seed to report output

### ISSUE THREAD

**Issue by kevinrobinson** [johnbintz/jasmine-headless-webkit#86]
This gem is great - thanks for all your work on it.

I noticed that the output from --report doesn't include the seed number that was used.  Can we add this in?  I looked through the source to try to figure it out and  it looks like the Ruby runner is passing the option into the jasmine-webkit-specrunner.  So we'd have to pass the seed in when calling the specrunner, which is straightforward.

But I was trying to figure out where to add the output in to the specrunner and kind find where the output format of the report is expressed.  I can track into the Runner::print() method in jasmine-webkit-specrunner/Runner.cpp but am not sure where to go from there.

If you can add this it would be great, or point me in the right direction and I try to add it in.  Or if there's already a better way to do this that's even better!

Thanks!
-Kevin

**Comment by johnbintz** [comment]
You need to go to three places to add this:
- Have the Qt runner accept the current seed as an argument. That's all in `ext` and `lib/jasmine/headless/runner.rb`.
- Create a new report message type in `lib/jasmine/headless/report_message/` for seed.
- Add that seed to the report output in the HeadlessReporter reporter in `vendor/assets/coffeescripts/jasmine.HeadlessReporter.coffee` just like how the other lines are added.

It's best to do any hacking on this while Guard is running, so that everything gets processed -- the Qt widget gets recompiled, the CoffeeScript gets compiled, and the tests are all run. I definitely won't have time to add this in the next few weeks, so if you want to take a stab at it, go right ahead. :)

If you have any other questions, let me know.

**Comment by kevinrobinson** [comment]
Thanks a lot!

So I started working on this and want to get Guard running to make sure I'm not breaking anything.  But when I run Guard at the command line I get this error:

```
$ guard
ERROR: Could not load 'guard/jasmine-headless-webkit' or find class Guard::Jasmineheadlesswebkit
ERROR: cannot load such file -- guard/jasmine-headless-webkit
ERROR: Invalid Guardfile, original error is:
undefined method `new' for nil:NilClass
```

I did `gem install jasmine-headless-webkit` in the current gemset, but still get this error.  Is there something else I need to configure to get this working?

Thanks again for your help and getting me started on my first little contribution to an open source project!
-Kevin

**Comment by johnbintz** [comment]
Do `bundle install` then `bundle exec guard`.

**Comment by kevinrobinson** [comment]
Got it, thanks for the help!

**Comment by johnbintz** [comment]
So I was working on redoing all the reporter stuff and I know you were messing around with this, but it was really easy for me to add making the seed accessible to reporters while I was working. This is in HEAD right now. I really really appreciate you offering to work on this (really!) but I just got to it first. :)

Take it for a spin and, along with all the new reporter stuff, let me know how it works for you!

**Comment by kevinrobinson** [comment]
John,

Thanks a lot, this is great!  I haven't had time to work on this and appreciate that you created this project and can keep updating it.

I know I can pull the repository down, compile it and install it into my project, but is there a way to just update my project's Gemfile and have bundler pull down the latest?  It doesn't look like these have commits have a version bump, so I assume there's no way to do this other than manually, is that right?

Thanks again for a great project that's a huge part of our development platform.
-Kevin

**Comment by johnbintz** [comment]
``` ruby
gem 'jasmine-headless-webkit', :git => 'git://github.com/johnbintz/jasmine-headless-webkit.git'
```

Then do `bundle update` when you want to grab the latest verison.

**Comment by kevinrobinson** [comment]
Thanks again!

**Comment by johnbintz** [comment]
Working on latest HEAD. Closing this. Reopen if you are having any problems.

**Comment by anton-yordanov** [comment]
ERROR: Could not load 'guard/jasmine-headless-webkit' or find class Guard::Jasmineheadlesswebkit
ERROR: cannot load such file -- guard/jasmine-headless-webkit
ERROR: Invalid Guardfile, original error is:
undefined method `new' for nil:NilClass

I have this error too with ruby-1.9.3-p0/Rails 3.2.6./Qt 4.7
I try everything that you describe in this issue  but without  luck
