### ISSUE TITLE
Performance drops between a18100bb71 0.8.3

### ISSUE THREAD

**Issue by christiannelson** [johnbintz/jasmine-headless-webkit#91]
Our specs slowed down and runtimes became more erratic between rev a18100bb71 and 0.8.3. Here are some run times:

**a18100bb71e58aa91f79f26634899093d4632877**

PASS: 141 tests, 0 failures, 2.775 secs.
PASS: 141 tests, 0 failures, 2.979 secs.
PASS: 141 tests, 0 failures, 2.906 secs.
PASS: 141 tests, 0 failures, 2.875 secs.

**0.8.3**

PASS: 141 tests, 0 failures, 14.548 secs.
PASS: 141 tests, 0 failures, 8.965 secs.
PASS: 141 tests, 0 failures, 3.369 secs.
PASS: 141 tests, 0 failures, 6.976 secs.

The only thing that's different between the two is the version of JHW. Any idea what might be the cause?

**Comment by johnbintz** [comment]
No idea, since some of the changes were actually to increase performance. Can you do a git bisect operation to find the commit that makes the biggest difference on your code test times?

**Comment by christiannelson** [comment]
That's what I thought, which is why I was surprised to see this. I know how to use git bisect to search revisions of own our repo. How can I use it to search versions of a dependent gem (JHW)?

**Comment by johnbintz** [comment]
If you're using a Gemfile, clone the repo to a local path and point the Gemfile at the path:

``` ruby
#gem 'jasmine-headless-webkit', '~> 0.8.0'
gem 'jasmine-headless-webkit', :path => '../jasmine-headless-webkit'
```

**Comment by christiannelson** [comment]
Thanks. I bisected using a script that cleaned out the compiled cpp (using git clean -Xf) and then ran my suite 3 times.

Here's the log, with results mixed in:

git bisect start

**bad: [7dde9328dfac2cbfc05c22c45efea7818d737294] add lib/ and app/ to vendored assets search, fixes #93**
git bisect bad 7dde9328dfac2cbfc05c22c45efea7818d737294

**good: [a18100bb71e58aa91f79f26634899093d4632877] move the jquery console test to the right spot**
PASS: 144 tests, 0 failures, 3.245 secs.
PASS: 144 tests, 0 failures, 3.214 secs.
PASS: 144 tests, 0 failures, 3.348 secs.
git bisect good a18100bb71e58aa91f79f26634899093d4632877

**good: [03a381d3cccf9abd3c10989ec72bd27979690827] prevent crazy onload loop, perhaps?**
PASS: 144 tests, 0 failures, 3.243 secs.
PASS: 144 tests, 0 failures, 3.238 secs.
PASS: 144 tests, 0 failures, 3.231 secs.
git bisect good 03a381d3cccf9abd3c10989ec72bd27979690827

**bad: [5d504570fd5c6398a8ae04e439eaa744b4598fbd] small refactoring**
PASS: 144 tests, 0 failures, 8.584 secs.
PASS: 144 tests, 0 failures, 19.549 secs.
PASS: 144 tests, 0 failures, 13.137 secs.
git bisect bad 5d504570fd5c6398a8ae04e439eaa744b4598fbd

**bad: [0d4562119f80cc36ea27620d42d995eb17e61252] small speed optimization**
PASS: 144 tests, 0 failures, 11.746 secs.
PASS: 144 tests, 0 failures, 5.471 secs.
PASS: 144 tests, 0 failures, 9.436 secs.
git bisect bad 0d4562119f80cc36ea27620d42d995eb17e61252

**bad: [3fe66c66c5eeba9c0d96147ff6ae3f0700dc13fd] specify the random order seed with --seed**
PASS: 144 tests, 0 failures, 13.457 secs.
PASS: 144 tests, 0 failures, 9.546 secs.
PASS: 144 tests, 0 failures, 6.806 secs.
git bisect bad 3fe66c66c5eeba9c0d96147ff6ae3f0700dc13fd

**bad: [f8db0522810abab51827923f7322676565107972] randomize spec load order because why not**
PASS: 144 tests, 0 failures, 4.362 secs.
PASS: 144 tests, 0 failures, 11.755 secs.
PASS: 144 tests, 0 failures, 7.424 secs.
git bisect bad f8db0522810abab51827923f7322676565107972

Not only did the times increase, the time varies pretty wildly. Weird.

**Comment by johnbintz** [comment]
lol wut. I can honestly say I have no clue off the top of my head what the heck is going on. I can try taking a closer look next week, but other projects are diverting my attention from hardcore JHW hacking lately. :/

If your digging uncovers anything else, please post it here so I can use it to figure out what the deal is.

**Comment by christiannelson** [comment]
Yeah, seriously. It's pretty weird. I'll poke around some more to see if I can unearth additional useful information.

**Comment by christiannelson** [comment]
@johnbintz It gets weirder... commenting out this line in 0.8.4 fixes the problem:

`files.sort! { |a, b| Kernel.rand(3) - 1 } if type == 'spec_files'`

And changing it to this also causes the massive slowdown:

`files.reverse! if type == 'spec_files'`

Can you think of anything else that might rely on the order of that array remaining unchanged?

When JHW is running slower, one of the cpus is pegged. So, it's busy doing something, though I don't know what.

We're going to dive deeper tomorrow (if we can) and see if we can shed some light on it. If you have any suggestions, please share. :)

**Comment by christiannelson** [comment]
Big surprise, it was an issue with our test suite that randomization uncovered, as intended. Thanks for bearing with that.
