### ISSUE TITLE
IFRAME src can't be set when running through jasmine-headless-webkit

### ISSUE THREAD

**Issue by kevinrobinson** [johnbintz/jasmine-headless-webkit#92]
I'm trying to use Jasmine to do full integration testing.  So in the beforeEach() we add an IFRAME to the page, set its src to my full app and then the Jasmine specs can work as integration tests in this way.  In this case it just checks that there is an element #email on the page.  This works great in the browser (Chrome).  Here's an example spec:

``` javascript
describe("UI", function() {
  it('mooooooooo', function() {
    //since the Jasmine server and the full app are running on different ports
    document.domain = document.domain;

    var sandboxWindow = null;
    var sandboxDocument = null;
    var sandboxLoaded = false;
    var $iframe = $('<IFRAME id="sandbox" />');
    var testPageURL = 'http://domain.com:7080/signin';    

    runs(function() {
      $iframe.attr('src', testPageURL);
      $iframe.load(function() {
        sandboxWindow = $iframe[0].contentWindow;
        sandboxDocument = $iframe[0].contentDocument;
        sandboxLoaded = true;
      });
      $('body').append($iframe);
    });

    waitsFor(function() {
      return sandboxLoaded;
    }, "iframe did not load", 10000);

    runs(function() {
      expect(sandboxWindow.$(sandboxDocument).find('#email').length).toEqual(1);
    })
  });
});
```

And this works great in Chrome.  The problem is that this throws an error when running the same spec through jasmine-headless-webkit (on Red Hat).  It says:

```
$ jasmine-headless-webkit

Running Jasmine specs...
........................Can't load file:///home/username/project/jhw.13792.html, the file may be broken.
Out of curiosity, did your tests try to submit a form and you haven't prevented that?
Try running your tests in your browser with the Jasmine server and see what happens.

Test ordering seed: --seed 596
```

I figure this is because of differences between QtWebkit and Chrome and I know what I'm doing is stretching the bounds a little.  But it would be great if we can write integration tests this way because then they can be written in Javascript and Jasmine and be debugged in Web Inspector.  It just seems like a better solution than using something like Capybara where there's a DSL and Ruby layer on top of what I really want to do, which is write my tests in Javascript, Jasmine-style.

I found this post http://distillations.2rye.com/2011/11/jasmine-headless-vs-in-browser/! which mentions the same problem and concludes they just can't run these kinds of tests headlessly.  And while this is helpful and a decent workaround, it means this approach won't really work for CI.  I don't know enough about how this works under the hood or the internals of QtWebkit so not really sure where to even start looking into this.

Any thoughts?

Thanks,
Kevin

**Comment by johnbintz** [comment]
I don't myself have any plans to add any sort of integration testing features to jasmine-headless-webkit, since it's designed to be strictly a unit testing tool. The closest you'd be able to get to what you want is if you use PhantomJS, which actually hits a running server, say one that has a Jasmine test suite on it.

The reason for your specific error is that jasmine-headless-webkit runs by loading an HTML page from the filesystem into the WebKit widget, and it actively looks to make sure you're not trying to load any other files or leave the page that the tests are running on. This is to make sure that, when firing jQuery events and the like, you don't have any unhandled events that could cause problems when running on a real page.

**Comment by kevinrobinson** [comment]
Hi John,

Thanks for the thorough and quick response!  I understand what you're saying about using PhantomJS to hit the Jasmine server, and see how I might be able to make that work.

What I really going for here is a way to write integration tests for my Javascript-heavy Rails app in Javascript using the same Jasmine style that I'm writing the unit tests in.  I know that this is not how Jasmine was intended to be used.  But writing integration tests in Ruby with Capybara and page.execute() seems like a very unnatural way to do integration testing for an app that is 90% Javascript.

Do you know of any other ways people have tackled this?

Thanks a lot,
Kevin

**Comment by johnbintz** [comment]
No clue how others have done it. But you may be able to get pretty far with PhantomJS, if you treat it like Capybara. The trick would be resetting the database after each run, but that could just be an Ajax call to a controller that only exists in `:acceptance`. You may want to hit the Twitters and see if anyone else is doing anything like this.

**Comment by kevinrobinson** [comment]
Hi John,

That's the other approach I was thinking about, so good to know I'm not talking crazy.  Thanks a lot for your information and keep up the good work!

Thanks,
Kevin
